# Required to run your project under the correct environment.
# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
 - 5.4
 - 5.5
 - 5.6

services:
  - memcached

# before start compiling services
before_script:
  - composer self-update
  - phpenv rehash
  - composer install
  - composer show -i
  - sh ./build/phalcon.sh
  - php --version
  - php -m | grep -i Phalcon
